In [1]:
## Import dependencies 

import pandas as pd

In [2]:
## Read CSV file into Pandas DataFrame from URL 
## The target URL is the ASX company directory, this data will be scraped and stored in a PostgreSQL database 
## Creating a web-scraping programme will enable the database to be updated automatically when new companies are added to the index 

# Create URL object, assigning the target URL 

URL = "https://asx.api.markitdigital.com/asx-research/1.0/companies/directory/file?access_token=83ff96335c2d45a094df02a206a39ff4"

# Create data object to store results, use pd.read_csv to return DataFrame 

data = pd.read_csv(URL)    

# Print results 

data

,ASX code,Company name,GICs industry group,Listing date,Market Cap
0,14D,1414 DEGREES LIMITED,Capital Goods,12/09/2018,10685244
1,1AD,ADALTA LIMITED,"Pharmaceuticals, Biotechnology & Life Sciences",22/08/2016,8800309
2,1AE,AURORA ENERGY METALS LIMITED,Materials,18/05/2022,10161033
3,1AG,ALTERRA LIMITED,"Food, Beverage & Tobacco",16/05/2008,6965525
4,1CG,ONE CLICK GROUP LIMITED,Capital Goods,28/04/2017,5487227
...,...,...,...,...,...
2053,ZLD,ZELIRA THERAPEUTICS LIMITED,"Pharmaceuticals, Biotechnology & Life Sciences",28/07/2003,17247676
2054,ZMI,ZINC OF IRELAND NL,Materials,18/09/2007,4689174
2055,ZMM,ZIMI LIMITED,Technology Hardware & Equipment,10/09/2007,3514331
2056,ZNC,ZENITH MINERALS LIMITED,Materials,29/05/2007,33123803
2057,ZNO,ZOONO GROUP LIMITED,Materials,21/07/1988,7217252

In [4]:
# Add the .AX suffix to the ASX code, this is required to exectue the yahooquery search

data['ASX code'] = data['ASX code'].astype(str) + '.AX'  

# Print results 

data

,ASX code,Company name,GICs industry group,Listing date,Market Cap
0,14D.AX,1414 DEGREES LIMITED,Capital Goods,12/09/2018,10685244
1,1AD.AX,ADALTA LIMITED,"Pharmaceuticals, Biotechnology & Life Sciences",22/08/2016,8800309
2,1AE.AX,AURORA ENERGY METALS LIMITED,Materials,18/05/2022,10161033
3,1AG.AX,ALTERRA LIMITED,"Food, Beverage & Tobacco",16/05/2008,6965525
4,1CG.AX,ONE CLICK GROUP LIMITED,Capital Goods,28/04/2017,5487227
...,...,...,...,...,...
2053,ZLD.AX,ZELIRA THERAPEUTICS LIMITED,"Pharmaceuticals, Biotechnology & Life Sciences",28/07/2003,17247676
2054,ZMI.AX,ZINC OF IRELAND NL,Materials,18/09/2007,4689174
2055,ZMM.AX,ZIMI LIMITED,Technology Hardware & Equipment,10/09/2007,3514331
2056,ZNC.AX,ZENITH MINERALS LIMITED,Materials,29/05/2007,33123803
2057,ZNO.AX,ZOONO GROUP LIMITED,Materials,21/07/1988,7217252